// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CmykToRgb(arg1:number,arg2:number,arg3:number,arg4:number):Promise<main.Rgb>;

export function HandleAlphaPointWiseTransformations(arg1:number,arg2:string):Promise<string>;

export function HandleBinarizeManual(arg1:string,arg2:number):Promise<string>;

export function HandleBinarizePercentBlack(arg1:string,arg2:number):Promise<string>;

export function HandleFilterApplying(arg1:string):Promise<string>;

export function HandleHistogram(arg1:string):Promise<string>;

export function HandleRgbPointWiseTransformations(arg1:Array<string>,arg2:string):Promise<string>;

export function HandleToGrayPointWiseTransformations(arg1:string,arg2:string):Promise<string>;

export function RgbToCmyk(arg1:number,arg2:number,arg3:number):Promise<main.Cmyk>;

export function SaveCanvasImg(arg1:string,arg2:main.ImageFormat,arg3:Array<string>):Promise<void>;
