// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CmykToRgb(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CmykToRgb'](arg1, arg2, arg3, arg4);
}

export function HandleAlphaPointWiseTransformations(arg1, arg2) {
  return window['go']['main']['App']['HandleAlphaPointWiseTransformations'](arg1, arg2);
}

export function HandleBinarizeManual(arg1, arg2) {
  return window['go']['main']['App']['HandleBinarizeManual'](arg1, arg2);
}

export function HandleBinarizePercentBlack(arg1, arg2) {
  return window['go']['main']['App']['HandleBinarizePercentBlack'](arg1, arg2);
}

export function HandleFilterApplying(arg1) {
  return window['go']['main']['App']['HandleFilterApplying'](arg1);
}

export function HandleHistogram(arg1) {
  return window['go']['main']['App']['HandleHistogram'](arg1);
}

export function HandleRgbPointWiseTransformations(arg1, arg2) {
  return window['go']['main']['App']['HandleRgbPointWiseTransformations'](arg1, arg2);
}

export function HandleToGrayPointWiseTransformations(arg1, arg2) {
  return window['go']['main']['App']['HandleToGrayPointWiseTransformations'](arg1, arg2);
}

export function RgbToCmyk(arg1, arg2, arg3) {
  return window['go']['main']['App']['RgbToCmyk'](arg1, arg2, arg3);
}

export function SaveCanvasImg(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveCanvasImg'](arg1, arg2, arg3);
}
