// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetJobStatus(arg1) {
  return window['go']['main']['Worker']['GetJobStatus'](arg1);
}

export function UploadNetPbmImg() {
  return window['go']['main']['Worker']['UploadNetPbmImg']();
}
